export const state = {
    parquetWasmInitialized: false,
    db: null,
    conn: null,
    isInitializing: false,
    isActive: false,
    eventCount: 0,
    sessionEventCount: 0,
    longevityState: {},
    previousTopics: new Set(),
    sessionStartTime: Date.now(),
    firstEventTime: null,
    lastEventTime: null,
    cachedDbSize: "0 B",
    lastUpdateDurationMs: null,
    activeBskyTabId: null,
    lastRawJsonString: null,
    lastFlutterTime: null,
    lastMigrationTime: null,
    totalScheduledDelayMs: 0,
    monitorTimeoutId: null,
    currentRateLimit: null,
    isLoggedIn: false,
    hasCheckedAuth: false,
    activeAuthHeaders: null,
    appPasswordHeaders: null
};
